// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4z_VZHSMsbNgVQgSUajP72yO-vS4q5lo',
    appId: '1:756812204046:web:5cd55b65f5bb2570c8945f',
    messagingSenderId: '756812204046',
    projectId: 'appointment-8d641',
    authDomain: 'appointment-8d641.firebaseapp.com',
    storageBucket: 'appointment-8d641.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4z_VZHSMsbNgVQgSUajP72yO-vS4q5lo',
    appId: '1:756812204046:android:5cd55b65f5bb2570c8945f',
    messagingSenderId: '756812204046',
    projectId: 'appointment-8d641',
    storageBucket: 'appointment-8d641.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4z_VZHSMsbNgVQgSUajP72yO-vS4q5lo',
    appId: '1:756812204046:ios:5cd55b65f5bb2570c8945f',
    messagingSenderId: '756812204046',
    projectId: 'appointment-8d641',
    storageBucket: 'appointment-8d641.firebasestorage.app',
    iosBundleId: 'com.sumerudigital.appointmentv1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4z_VZHSMsbNgVQgSUajP72yO-vS4q5lo',
    appId: '1:756812204046:ios:5cd55b65f5bb2570c8945f',
    messagingSenderId: '756812204046',
    projectId: 'appointment-8d641',
    storageBucket: 'appointment-8d641.firebasestorage.app',
    iosBundleId: 'com.sumerudigital.appointmentv1',
  );
}
